#!/bin/sh

if [ $# -eq 0 ]; then
    progname="`basename $0`"
    cat <<EOM
$progname - Just almost same as 'git-rm {arg}; git-add {arg}'
Usage: $progname {dir_or_file}
EOM
    exit 1
fi

if [ -d "$1" ]; then
    git rm --cached -r -- "$1" && git add -- "$1"
else
    git add -- "$1"
fi
