#!/bin/sh

# git-spp
#
# Do `git stash pop` even if working tree is dirty.

true=:
false=/bin/false

is_dirty() {
    if [ -z "`git diff`" ]; then
        echo $false
    else
        echo $true
    fi
}

dirty=`is_dirty`
if $dirty; then
    git commit --all --quiet -m '*temp* (git-spp)'
fi
git stash pop
if $dirty; then
    git commit --amend --all --quiet -m '*temp* (git-spp)'
    git reset --quiet HEAD~
fi
