#!/bin/sh
# via http://labs.timedia.co.jp/2011/03/git-removing-a-submodule.html

if [ ! -z "`git rev-parse --show-cdup`" ]; then
    echo "error: git-submodule can be run at top level of repository." >&2
    exit 1
fi
if [ ! -z "`git diff HEAD -- .gitmodules`" ]; then
    echo "error: .gitmodules is dirty. please commit or junk its hunk." >&2
    exit 1
fi
if [ $# -eq 0 ]; then
    echo "Usage: $(basename $0) {submodule1} [{submodule2} ...]" >&2
    exit 1
fi


quiet=
if [ "$1" = "--quiet" ]; then
    quiet="--quiet"
    shift
fi

set -e
for name in "$@"; do
    git rm $quiet --cached `git config --file .gitmodules --get submodule.$name.path`
    git config --file .gitmodules --remove-section submodule.$name
    git add .gitmodules
done
