#!/bin/sh
# via http://labs.timedia.co.jp/2011/03/git-removing-a-submodule.html

if [ ! -z "`git rev-parse --show-cdup`" ]; then
    echo "error: git-submodule can be run at top level of repository." >&2
    exit 1
fi
if [ ! -z "`git diff HEAD -- .gitmodules`" ]; then
    echo "error: .gitmodules is dirty. please commit or junk its hunk." >&2
    exit 1
fi
if [ $# -eq 0 ]; then
    echo "Usage: $(basename $0) {submodule1} [{submodule2} ...]" >&2
    exit 1
fi


quiet=
cached=
while [ $# -ne 0 ]; do
    case "$1" in
        --quiet)
            quiet="--quiet"
            ;;
        --cached)
            cached="--cached"
            ;;
        *)
            break 2
            ;;
    esac
    shift
done

set -e
for name in "$@"; do
    path="`git config --file .gitmodules --get submodule.$name.path`"
    git rm $quiet --cached "$path"
    if [ -z "$cached" ]; then
        rm -rf "$path"
    fi
    git config --file .gitmodules --remove-section submodule.$name
    git add .gitmodules
done
