#!/bin/sh

is_dirty() {
    if [ -z "`git diff`" ]; then
        return $false
    else
        return $true
    fi
}
cleanup() {
    if is_dirty; then
        echo 'failed to clean up: dirty working tree.' >&2
        return 1
    fi
    if [ "`git stash list`" ]; then
        echo 'failed to clean up: `git stash list` is not empty.' >&2
        return 2
    fi
    if [ "`git branch | egrep -v '^[* ] master$'`" ]; then
        echo 'failed to clean up: branch is not only master.' >&2
        return 3
    fi
    return 0
}


if [ $# -eq 0 ]; then
    echo "Usage: $(basename $0) {repodir}" >&2
    exit 1
fi
repo="$1"

if [ ! -d "$repo" ]; then
    echo "$repo: No such directory" >&2
    exit 2
fi
(cd "$repo" && cleanup) && rm $repo
