#!/bin/sh

usage () {
    progname="`basename $0`"
    cat <<EOM
$progname - *Really* remove given files from git objects
Usage: $progname <file>
EOM
    exit 1
}


[ $# -eq 0 ] || usage
command git filter-branch \
    -f --index-filter \
    "git update-index --remove '$1'" HEAD
