#!/bin/sh


usage() {
    # TODO: Description about options, arguments, and so on.
    progname="`basename $0`"
    cat <<EOM
$progname - Remove repository's directory safely.
Usage: $progname {repodir}
EOM
    exit 1
}
warn() {
    echo "$@" >&2
}
die() {
    echo "$@" >&2
    exit 1
}
is_git_repo() {
    return 0 # TODO
}
ready_to_destroy() {

    if ! is_git_repo; then
        warn "warning: Not a git repository."
        return 1
    fi
    if [ "`git show 2>&1 >/dev/null`" = "fatal: bad default revision 'HEAD'" ]; then
        warn "warning: empty repository."
        return 0
    fi
    if [ "`git diff`" ]; then
        warn "warning: dirty working tree."
        return 2
    fi
    if [ "`git stash list`" ]; then
        warn "warning: 'git stash list' is not empty."
        return 3
    fi
    if [ "`git branch | egrep -v '^[* ] master$'`" ]; then
        warn "warning: branch is not only master."
        return 4
    fi
    # TODO: Check if there is unpushed commits

    return 0
}


# Parse arguments
check_only=false
quiet=false
while [ $# -ne 0 ]; do
    case "$1" in
        -c|--check-only) check_only=true ;;
        -q|--quiet) quiet=true ;;

        --) shift; break ;;
        -*) echo "Unrecognized option: $1" >&2; exit 2 ;;
        *)  break ;;
    esac
    shift
done
[ $# -eq 0 ] && usage


# Main
for repo in "$@"; do
    if [ ! -d "$repo" ]; then
        warn "$repo: No such directory"
        continue
    fi

    (cd "$repo" && ready_to_destroy)
    exit_code=$?

    if $check_only; then
        # Tell if $repo is clean repository. (--check-only)
        if $quiet; then
            # Tell by return code. (--quiet)
            # NOTE: To check multiple $repo as possible,
            # do not exit if $exit_code -eq 0 .
            [ $exit_code -ne 0 ] && exit $exit_code
        else
            if [ $exit_code -eq 0 ]; then
                echo "$repo: ok"
            else
                echo "$repo: not ok: Check commits, stashes, branches, and so on."
            fi
        fi
    else
        rm -fr "$repo"
    fi
done
exit 0
