#!/bin/sh

src=
dest=
dest_url=

usage() {
    progname="`basename $0`"
    cat <<EOM
$progname - Rename submodule easily
Usage: $progname {src} {dest} [{dest-url}]
EOM
}
die() {
    echo "$@" >&2
    exit 1
}
get_dest_url() {
    src="$1"
    git config -f .git/config --get submodule."$src".url
}
validate() {
    src="$1"
    dest="$2"
    dest_url="$3"

    [ -d "$src" ]        || die "error: source submodule '$src' does not exist."
    [ ! -e "$dest" ]     || die "error: destination path '$dest' exist."
    [ ! -z "$dest_url" ] || die "error: destination submodule url is empty."
}

case $# in
    2)
        src="$1"
        dest="$2"
        dest_url="`get_dest_url "$src"`"
        ;;
    3)
        src="$1"
        dest="$2"
        dest_url="$3"
        ;;
    *)
        usage
        ;;
esac
validate "$src" "$dest" "$dest_url"

# git-subrm exits with non-zero status
# when .gitmodules is dirty.
set -e
if [ "`ls $src`" ]; then
    # Non-empty repository.
    # ("git submodule update --init" was performed)
    # Remove repo directory and clone $dest_url repository.
    git subrm --quiet "$src"
    git submodule --quiet add "$dest_url" "$dest"
else
    # Empty repositry. Just rewrite .gitmodules.
    git subrm --quiet --cached "$src"
    mv "$src" "$dest"
    # Ignore "Adding existing repo at 'foo' to the index" message.
    git submodule --quiet add "$dest_url" "$dest" 2>/dev/null || true
fi

echo "Successfully renamed '$src' to '$dest' ($dest_url)."
