#!/usr/bin/env perl
use strict;
use warnings;
use utf8;

use Getopt::Long qw(:config gnu_compat no_bundling no_ignore_case);
use Pod::Usage;
use Git;
use Cwd qw(getcwd);
use File::Spec::Functions qw(canonpath);


sub usage () {
    pod2usage(-verbose => 2);
}


my $needhelp;
GetOptions(
    'h|help' => \$needhelp,
) or usage;
usage if $needhelp;
usage if @ARGV != 2;


my ($path, $repo_path) = @ARGV;
my $cwd = getcwd();
my $repo = Git->repository($cwd);

die "$repo_path:$!\n"
    if -e $repo_path;
die "You need to run this command from the toplevel of the working tree.\n"
    unless canonpath($repo->wc_path) eq canonpath($cwd);




__END__

=head1 NAME

    git-split-submodules - split a path to indivisual repository (submodule).


=head1 SYNOPSIS

    $ git split-submodules path/from/top/repo /path/to/submodule

    # now 'path/from/top/repo' becomes submodule.
    # and repository is at '/path/to/submodule'.

=head1 AUTHOR

tyru <tyru.exe@gmail.com>
