#!/bin/sh


dir=
remote="backup"
branch="master"

usage() {
    cat <<EOM
git-push-backup - Push branch given remote

NOTE: now I guess this is totally useless
because 'git push --all' does the job.

Usage: git-push-backup {repos_dir} [{remote} [{branch}]]
EOM
    exit 1
}


for varname in dir remote branch; do
    if [ $# -ne 0 ]; then
        eval "$varname=\"$1\""
        shift
    else
        break
    fi
done

[ -z "$dir" ] && usage
cd "$dir" || exit $?

for repo in `ls`; do
    # TODO: log forced-update?
    (cd "$repo" && git push -f "$remote" "$branch" >/dev/null 2>&1)
done
