#!/bin/sh

usage() {
    progname="`basename "$0"`"
    cat <<EOM >&2
USAGE
    $progname {file}                    (1)
    $progname {file} {repo dir}         (2)
    $progname {file1}{file2} {repo dir} (3)

SYNOPSIS
    (1)

    # create file/dir foo
    $ vim foo

    # create repo 'foo' and
    # original 'foo' will be moved to 'foo/foo'.
    $ $progname foo

    (2)

    # create file/dir foo
    $ vim foo

    # create repo 'foo' and
    # original 'bar' will be moved to 'foo/bar'.
    $ $progname bar foo

    (3)

    # create repo 'foo' and
    $ vim foo

    # create repo 'foo' and
    # original 'bar', 'baz' will be moved
    # to 'foo/bar', 'foo/baz'.
    $ $progname bar baz foo
EOM
    exit 1
}

create_tempfile() {
    file="`tempfile`"
    trap "rm -f '$file'" 0 HUP INT QUIT TERM
    echo "$file"
}
get_commit_msg() {
    echo hi
}


case $# in
    0) usage
       ;;
    1) file="`create_tempfile`"
       tar zhcf - "$1" >"$file" || exit $?
       rm -f "$1" || exit $?
       mkdir "$1" || exit $?
       cd "$1" || exit $?
       tar zpxf - <"$file"
       git init; git add .; git ci -m "`get_commit_msg`"
       ;;
    *) bar    # TODO
       ;;
esac
