#!/bin/sh


true=:
false=/bin/false

usage() {
    progname="`basename $0`"
    cat <<EOM
$progname - Do 'git stash pop' even if working tree is dirty.
Usage: $progname {src} {dest} [{dest-url}]
EOM
}
is_dirty() {
    if [ -z "`git diff`" ]; then
        echo $false
    else
        echo $true
    fi
}

dirty=`is_dirty`
if $dirty; then
    git commit --all --quiet -m '*temp* (git-spp)'
fi
git stash pop
if $dirty; then
    git commit --amend --all --quiet -m '*temp* (git-spp)'
    git reset --quiet HEAD~
fi
